services:
  telegrambot:
    build: .
    container_name: telegrambot
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    pid: host
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS}
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /etc/systemd:/etc/systemd
      - /run/systemd:/run/systemd
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/hostapd:/etc/hostapd
      - /etc/dnsmasq.d:/etc/dnsmasq.d
      - /etc/NetworkManager:/etc/NetworkManager
      - /var/lib/NetworkManager:/var/lib/NetworkManager
      - /run/netns:/run/netns
      - /sys:/sys
      - /proc:/proc